[env]
# NDK 工具链路径
NDK_HOME = "D:\\Andriod sdk\\ndk\\28.2.13676358"
ANDROID_NDK_HOME = "D:\\Andriod sdk\\ndk\\28.2.13676358"
ANDROID_HOME = "D:\\Andriod sdk"
CC_aarch64-linux-android = "D:\\Andriod sdk\\ndk\\28.2.13676358\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android35-clang.cmd"
AR_aarch64-linux-android = "D:\\Andriod sdk\\ndk\\28.2.13676358\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"

[target.aarch64-linux-android]
linker = "D:\\Andriod sdk\\ndk\\28.2.13676358\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android35-clang.cmd"

[target.armv7-linux-androideabi]
linker = "D:\\Andriod sdk\\ndk\\28.2.13676358\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi35-clang.cmd"

[target.i686-linux-android]
linker = "D:\\Andriod sdk\\ndk\\28.2.13676358\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\i686-linux-android35-clang.cmd"

[target.x86_64-linux-android]
linker = "D:\\Andriod sdk\\ndk\\28.2.13676358\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android35-clang.cmd"
